apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spam-detection
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.example.com/your-org/spam-detection.git
    targetRevision: HEAD
    path: k8s/
  destination:
    server: https://kubernetes.default.svc
    namespace: spam-detection
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true